[redash]
url = "https://redash-vn.ninjavan.co"
api_key = "xzvZOOzHWacUXU7I5Ub7kfCQDYbvDSiQRmbd9pIL"

[queries]
query_1004 = "RSVN SHIPPER FAKEFAIL CHECK (1004)"
query_1204 = "LM Status Tracking (1204)"
query_1968 = "POD (1968)"
query_1921 = "Recovery Status (1921)"